services:
  tdsoftrepositoriesapi:
    image: tdsoft-repositoriesapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
    ports:
      - "5400:80"
    volumes: 
      - .:/app/